project:
  type: website

website:
  title: "Sam Parmar"
  navbar:
    left:
      - href: index.qmd
        text: About me
      - projects.qmd
      - href: https://parmsam.medium.com/
        text: Blog
    background: primary
    border: true
  search: 
    location: navbar
    type: overlay
    copy-button: true
  reader-mode: true
  favicon: images/glasses.ico
  page-footer: 
    left: "Created using [Quarto](https://quarto.org/docs/websites/). Opinions are my own." 
    right: 
      - icon: github
        href: https://github.com/parmsam
      - icon: linkedin
        href: https://www.linkedin.com/in/sam-parmar-/
      - icon: medium
        href: https://parmsam.medium.com/
      - icon: twitter 
        href: https://twitter.com/parmsam_
        

format:
  html:
    theme: 
      light: [Sandstone, theme.scss]
      dark: [Sandstone, theme-dark.scss]
    css: styles.css
    toc: true



