project:
  type: website

website:
  title: "Sam Parmar"
  navbar:
    left:
      - href: index.qmd
        text: About me
      - projects.qmd
      - href: https://parmsam.medium.com/
        text: Blog
  search: 
    location: navbar
    type: overlay
    copy-button: true
  favicon: images/glasses.ico

format:
  html:
    theme: 
      light: litera
      dark: [litera, theme-dark.scss]
    css: styles.css
    toc: true



