project:
  type: website

website:
  title: "Sam Parmar"
  navbar:
    left:
      - href: index.qmd
        text: About me
      - projects.qmd
      - href: https://parmsam.medium.com/
        text: Blog
  search: 
    location: navbar
    type: overlay
    copy-button: true
  favicon: images/bread-astro.png

format:
  html:
    theme: litera
    css: styles.css
    toc: true



