---
title: "Projects"
toc: true
---

### [Notification System for the Hearing Impaired](https://github.com/parmsam/notif-sys-hearing-impaired)

Notification system (set of programs) built around a Raspberry Pi to notify a hearing impaired individual of trigger sounds such as a baby crying or dog barking in their surrounding environment, with build instructions made publicly available. This project was created as part of the CS 498 Internet of Things class at University of Illinois Urbana-Champaign in Spring 2022.

-   Project Summary Video [here](https://uofi.app.box.com/s/v9yxjxhd81fyiyu9bq18glu1ux9lpe7g)

### [Interactivity with the deluxe cars dataset](https://github.com/parmsam/rstudio-table-contest-2021)

Interactive web page that shows a table of the gtcars dataset from the gt package. The data shows expensive and fast cars from 2014 to 2017. The webpage serves as an example of the many capabilities of the reactable and crosstalk packages in combination. Created for 2021 Rstudio Table Contest.

-   Webpage [here](https://parmsam.github.io/rstudio-table-contest-2021/rstudio-table-contest-2021-sam.html)

### [Mix things Up](https://github.com/parmsam/rstudio-table-contest-2021)

Simple Shiny app to quickly generate random workout plans from a list of exercises. Features the use of the gt and bslib packages as well as publishing to Google Sheets for import into Shiny.

-   Created as a part of judges submission (omitted from evaluation) for 2021 Rstudio [Shiny Contest.](https://www.rstudio.com/blog/winners-of-the-3rd-annual-shiny-contest/)

-   Shiny app [here](https://parmsam.shinyapps.io/MixThingsUp/)

### [Tables of USA COVID-19 Policy Orders](https://github.com/parmsam/rstudio-table-contest)

Interactive webpage created that shows COVID-19 Policy Orders data as of October 23, 2020 for USA states (first table) and counties (second tables) over time. Created for 2020 Rstudio Table Contest.

-   Webpage [here](https://parmsam.github.io/rstudio-table-contest/Sam-s-Rstudio-Table-Contest-Submission.html)

### [Prep4PrEP](https://github.com/parmsam/Prep4PrEP)

Simple Shiny app (proof of concept) based on Greater than AIDS information response content from KFF. Aimed to quickly educate and inform people on PrEP via a custom UI.

-   Shiny app [here](https://parmsam.shinyapps.io/Prep4PrEP/)

### [COVID-19 Vaccine Dose Waste in USA](https://github.com/parmsam/covid19-vaccine-dose-waste)

Set of plots examining COVID-19 vaccine dose waste in the USA. Data visualizations created using ggplot2.

-   Summary available [here](https://github.com/parmsam/covid19-vaccine-dose-waste/blob/main/README.md)

### [Multi-purpose Timer](https://github.com/parmsam/timer)

Timer webpage for studying, exercising, or meditating. Created for personal use.

-   Webpage [here](https://parmsam.github.io/timer/)

### [Indy HIV Test](https://github.com/parmsam/indy-hiv-test)

Simple redesign of indyhivtest.com to better inform persons living in Indianapolis on where they can get tested for HIV.

-Webpage [here](https://parmsam.github.io/indy-hiv-test/)

### [Sam's COVID 19 Dashboard](https://github.com/parmsam/covid-19-dashboard)

D3js interactive visualization on COVID-19 in USA implemented as an interactive web page.

-   Interactive webpage [here](https://parmsam.github.io/covid-19-dashboard/) (open in Chrome browser)

### [COVID 19 Narrative Viz Indy](https://github.com/parmsam/covid-19-narrative-viz-indy)

D3js narrative visualization on impact of COVID-19 in Indiana (as of June 24, 2020) implemented as an interactive web page for CS498 Data Visualization at UIUC in Summer 2020.

-   Interactive webpage [here](https://parmsam.github.io/covid-19-narrative-viz-indy/)

### [Air and Surface Decay of SARS-CoV-2 by US City](https://github.com/parmsam/air-surface-decay-SARS-CoV-2-by-US-city)

Shiny app that makes it easier for public health and public safety workers to get current location-specific/weather-specific SARS-CoV-2 airborne or surface decay estimates.

-   Shiny app [here](https://parmsam.shinyapps.io/Airborne_and_Surface_Decay_of_SARS_CoV-2_for_Major_Cities/)

### [One Source Indy](https://github.com/parmsam/one-source-indy)

Better informs in-need homeless or unstably-housed individuals living in Indianapolis on resources available in their community. The prototype was created to show how publicly available resource data can be used with R Shiny and to encourage others to develop similar applications for social good.

-   Runner up in Rstudio's 2020 [Shiny Contest.](https://blog.rstudio.com/2020/07/13/winners-of-the-2nd-shiny-contest/)

-   Shiny app [here](https://parmsam.shinyapps.io/one_source_indy/)

### [Spotify Sentiment Analysis](https://github.com/pragyamis/SpotifySentimentAnalysis)

Gives parents, with control over their son or daughter's Spotify accounts, a simple tool to analyze trends in listening history and understand emotional content of the listening choices. Simple JS web application.

### [Nationwide CDC Opioid Prescribing Rates Analysis](https://github.com/parmsam/cdc-opioid-prescribing-rates)

Web scraping from CDC public data tables to obtain opioid prescription rates data for past few years 2006-2017 at county and/or state level. Provided to public health partners in Indiana to support public health interventions.

### [National Weather Service Forecasts](https://github.com/parmsam/national-weather-service-forecasts)

Shiny app that allows users to obtain latest weather forecast data for 1000 largest cities in the US. Makes use of the National Weather Service API.

### [Viral Load Analysis Program](https://github.com/parmsam/viral-load-analysis)

Allows organizations with access to viral load results of people living with HIV to conduct analysis of community viral load.

-   Presented at 2018 Ryan White National Conference workshop.
